{   'name': 'Symptoms',
    'version': '1.0',
    'author': 'Mitosis Technologies',
    'summary': 'Symptoms and its negative impact in your life',
    'description': """Categories, Symptoms, Articles, Expert Advice and its Negative Impacts""",
    'category': 'Symptoms',
    'sequence': 1,
    'website': '',
    'depends': ['base','account','mail'],
    'data': ['security/ir.model.access.csv',
             'security/symptoms_rules.xml',
             'views/res_partner_views.xml',
             'views/symptoms_category_views.xml',
             'views/symptoms_impact_views.xml',
             'views/symptoms_symptoms_views.xml',
             'views/symptoms_articles_views.xml',
             'views/expert_advice_views.xml',
             'wizard/symptoms_info_wizard.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
 }